baseURL = 'https://www.benstrawbridge.com/'
defaultContentLanguage = 'en'
enableRobotsTXT = true
languageCode = 'en-us'
summaryLength = 100
timeout = "60s"
enableEmoji = true
enableGitInfo = true  # Disabled in default/local to avoid slower builds
theme = 'ryder-dev'
timeZone = "America/Los_Angeles"
title = "Ben Strawbridge Dot Com Consulting"
description = 'My place to work on my online projects and experiment with the web.'
copyright = '<i class="fa-regular fa-copyright"></i>  2026 benstrawbridge.com'
[params]
  description = 'Dot Com Consulting'
  TocOpen = true
  loadLeaflet = true 
  # UseHugoToc = true
  # enabledebugpanel = true 
  # navbar_fixed = true
  # homepage list exclusion... 
  excludedSections = ["fineprint", "portfolio", "goals", "consulting", "everything-everywhere"]
  excludedCategories = ["catalog"]
  showDarkToggle = true
  showShareButtons = true
  showSummaryMeta = false
  og_image_default = '/images/og/og_image_default.jpg'
  logo_png = '/images/bs_full_wordmark.png'
  logo_firstWord = 'ben'
  logo_lastWord = 'strawbridge'
  logo_tagline = "DOT COM CONSULTING"
  logo_fontClass = 'font-titillium'
  repository = "https://github.com/benstraw/benstrawbridge.com"
  amazon_associate_id = "benstrawbridge-20"
  footerLayout = "stacked"
  # cardCategoryColorsDefault = "bg-indigo-200"
  [params.shareButtons]
    networks = [ "email", "linkedin" ]
  [params.author]
    email = 'ben@benstrawbridge.com'
    name = 'Ben Strawbridge'
  [params.twClasses]
    headerBackgroundFrameOuter = "bg-gradient-to-r to-sky-300 from-indigo-300 dark:from-violet-950 dark:to-gray-900 border-b border-fuchsia-600 text-violet-950 dark:text-neutral-100"
    headerBackgroundFrameInner = "bg-header-sunset-sf-coke dark:bg-header-artist-date-two h-[200px] sm:h-[250px] bg-cover bg-bottom"
    # footerBackground = "bg-gradient-to-r from-violet-950 to-rose-950 border-fuchsia-600" 
    # navbar_fixed = "sticky top-0"
  [params.footer]
    tagCloud = true
# [[params.alphaAlert]]
#   weight = 1
#   alertType = "success"
#   alertTitle = "Ryder Theme for Hugo"
#   alertMessage = "Learn more about the theme by checking out the README on <a href='https://github.com/arts-link/ryder' class='underline'>on github.com</a>."
#   dismissable = true 
#   alertIconClass = "fa-solid fa-camera-retro"
[pagination]
  pagerSize = 24 

[markup]
  [markup.highlight]
    linenos = false
[taxonomies]
  ingredient = 'ingredients'
  musical-genre = 'musical-genres'
  tag = 'tags'
  category = 'categories'
[permalinks]
  post = "/:year/:month/:title/"
  
[menu]
[[menu.recipes]]
    name = 'Why?'
    url = '/recipes/about/'
    weight = 40
[[menu.recipes]]
    name = 'Recipe Index'
    url = '/recipes/'
    weight = 30
