theme = "ryder"
# enableGitInfo = true  # Disabled for 40-50% faster builds. See theme docs for details.

[params]
  env = "production"
  plausible_domain = "benstrawbridge.com"
  plausible_advanced = true

# [services]
#   [services.googleAnalytics]
#     ID = 'G-6ZYXDDEJQW'